// Generated by scripts/build-tokens.mjs from tokens/tokens.json (layout). Do not edit by hand.
export const BREAKPOINTS = { tablet: 768, desktop: 1024, wide: 1440 } as const;
export type Breakpoint = "mobile" | keyof typeof BREAKPOINTS;
