// Generates src/styles/theme.css from tokens/tokens.json.
// tokens.json is exported from the Figma library; never edit theme.css by hand.
import { readFileSync, writeFileSync } from "node:fs";

const t = JSON.parse(readFileSync(new URL("../tokens/tokens.json", import.meta.url)));
const vars = [];
const theme = [];

const walk = (obj, prefix, toTheme) => {
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith("$")) continue;
    const name = `${prefix}-${k}`;
    if (typeof v === "object") walk(v, name, toTheme);
    else {
      vars.push(`  --inova${name}: ${v};`);
      if (toTheme) theme.push(`  ${toTheme(name)}: var(--inova${name});`);
    }
  }
};

walk(t.color, "-color", (n) => n.replace("-color-", "--color-"));
walk(t.radius, "-radius", (n) => n.replace("-radius-", "--radius-"));
for (const [k, v] of Object.entries(t.spacing)) walk(v, `-spacing-${k}`);
for (const [k, v] of Object.entries(t.size)) vars.push(`  --inova-size-${k}: ${v}px;`);
for (const [k, v] of Object.entries(t["border-width"])) vars.push(`  --inova-border-width-${k}: ${v}px;`);
for (const [k, v] of Object.entries(t.effect)) vars.push(`  --inova-${k}: ${v}px;`);
vars.push(`  --inova-safe-area-top: env(safe-area-inset-top, ${t["safe-area"]["top-fallback"]}px);`);
for (const [k, v] of Object.entries(t.font.size)) {
  vars.push(`  --inova-font-size-${k}: ${v}px;`);
  theme.push(`  --text-${k}: var(--inova-font-size-${k});`);
  if (t.font["line-height"][k]) theme.push(`  --text-${k}--line-height: var(--inova-line-height-${k});`);
}
for (const [k, v] of Object.entries(t.font["line-height"])) vars.push(`  --inova-line-height-${k}: ${v}px;`);
for (const [k, v] of Object.entries(t.font.weight)) vars.push(`  --inova-font-weight-${k}: ${v};`);
vars.push(`  --inova-font-sans: var(--font-inter, "${t.font.family.sans}"), ui-sans-serif, system-ui, sans-serif;`);
vars.push(`  --inova-font-serif: var(--font-instrument-serif, "${t.font.family.serif}"), ui-serif, Georgia, serif;`);
vars.push(`  --inova-font-mono: var(--font-roboto-mono, "${t.font.family.mono}"), ui-monospace, monospace;`);
theme.push("  --font-sans: var(--inova-font-sans);", "  --font-serif: var(--inova-font-serif);", "  --font-mono: var(--inova-font-mono);");
// px values for numeric scales
const px = (s) => s.replace(/: (\d+);$/, ": $1px;");
const lines = vars.map((l) => (/--inova-(radius|spacing)/.test(l) ? px(l) : l));

// motion: durations (ms) and easings; Tailwind gets --ease-enter/exit/standard for ease-* utilities.
for (const [k, v] of Object.entries(t.motion.duration)) lines.push(`  --inova-motion-duration-${k}: ${v}ms;`);
for (const [k, v] of Object.entries(t.motion.easing)) {
  lines.push(`  --inova-motion-easing-${k}: ${v};`);
  if (k !== "linear") theme.push(`  --ease-${k}: var(--inova-motion-easing-${k});`);
}

// layout: breakpoints, grid and menu widths. Each range overrides the grid variables from its min width up.
const L = t.layout;
const ranges = ["mobile", "tablet", "desktop", "wide"];
const gridVars = (r) => [
  `--inova-grid-columns: ${L[r].columns};`,
  `--inova-grid-gutter: ${L[r].gutter}px;`,
  `--inova-grid-margin: ${L[r].margin}px;`,
  `--inova-nav-width: ${L[r].nav}px;`,
  `--inova-content-max-width: ${L[r]["max-width"] ? L[r]["max-width"] + "px" : "none"};`,
];
lines.push(...gridVars("mobile").map((l) => `  ${l}`), `  --inova-nav-width-collapsed: ${L["nav-collapsed"]}px;`);
for (const r of ranges.slice(1)) theme.push(`  --breakpoint-${r}: ${L[r].min / 16}rem;`);
const layoutCss = ranges
  .slice(1)
  .map((r) => `@media (min-width: ${L[r].min}px) {\n  :root {\n${gridVars(r).map((l) => `    ${l}`).join("\n")}\n  }\n}`)
  .join("\n\n");

const css = `/* Generated by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit by hand. */
@import "tailwindcss";

:root {
${lines.join("\n")}
}

@theme inline {
${theme.map(px).join("\n")}
}

${layoutCss}

@keyframes inova-menu-in { from { opacity: 0; transform: translateX(-24px) } to { opacity: 1; transform: none } }
@keyframes inova-menu-out { from { opacity: 1; transform: none } to { opacity: 0; transform: translateX(-24px) } }
@keyframes inova-fade-in { from { opacity: 0 } to { opacity: 1 } }
@keyframes inova-fade-out { from { opacity: 1 } to { opacity: 0 } }
@keyframes inova-drawer-in { from { transform: translateX(calc(100% + 16px)) } to { transform: translateX(0) } }
@keyframes inova-drawer-out { from { transform: translateX(0) } to { transform: translateX(calc(100% + 16px)) } }
@keyframes inova-dialog-in { from { opacity: 0; transform: translateY(16px) } to { opacity: 1; transform: none } }
@keyframes inova-dialog-out { from { opacity: 1; transform: none } to { opacity: 0; transform: translateY(16px) } }

html {
  background-color: var(--inova-color-surface-canvas-bottom);
  background-image: linear-gradient(to top, var(--inova-color-surface-canvas-bottom) 0%, var(--inova-color-surface-canvas-top) 42%);
  color: var(--inova-color-text-primary);
  font-family: var(--inova-font-sans);
}
`;
writeFileSync(new URL("../src/styles/theme.css", import.meta.url), css);
console.log(`theme.css: ${lines.length} variables, ${theme.length} Tailwind mappings`);
